### PR TITLE
Missing new lines in reply messages.

### PR DESCRIPTION
**Pull request by jtcoolen**
They were missing new lines in the replies from coqbot, messing with the rendering of the details HTML tags.

### CODE REVIEW

**Comment by JasonGross** [comment]
Good catch, thanks!

**Comment by JasonGross** [comment]
Testing:

**Comment by JasonGross** [comment]
Testing:

**Comment by JasonGross** [comment]
Testing:

@coqbot minimize
```
# You can insert a bash script which produces the error message here,
# our bot will answer with a stripped down version of it.
# Example:
#opam install -y coq-ext-lib
#eval $(opam env)
#mkdir temp
#cd temp
#wget https://github.com/coq/coq/files/4698509/bug.v.zip
#unzip bug.v.zip
#coqc -q bug.v
```

**Comment by jtcoolen** [comment]
@coqbot minimize
```
# You can insert a bash script which produces the error message here,
# our bot will answer with a stripped down version of it.
# Example:
#opam install -y coq-ext-lib
#eval $(opam env)
#mkdir temp
#cd temp
#wget https://github.com/coq/coq/files/4698509/bug.v.zip
#unzip bug.v.zip
#coqc -q bug.v
```

**Comment by JasonGross** [comment]
@coqbot: run CI now

**Comment by JasonGross** [comment]
Testing:

@coqbot: run CI now

**Comment by JasonGross** [comment]
@coqbot: minimize it

```
opam install -y coq-ext-lib
eval $(opam env)

mkdir temp
cd temp
wget https://github.com/coq/coq/files/4698509/bug.v.zip
unzip bug.v.zip
coqc -q bug.v
```

**Pull request merged**
